### ISSUE TITLE
Bug: Mod fails to build

### ISSUE THREAD

**Issue by CheetahCyberBoi** [TeamGalacticraft/Galacticraft#132]
## Edit: This issue is caused by not having `git` installed. Please download it at [https://git-scm.com/downloads](https://git-scm.com/downloads).

---

### Galacticraft Version:
Latest prealpha from the main branch

### Game Logs ([gist](https://gist.github.com)):
None sadly, since i was compiling

### Multiplayer? (Yes, No, LAN):
No

### OS:
Windows 10 Latest

### Expected Behaviour:
Mod compiles and is runnable

### Actual Behaviour:
Gradle outputs a error on line 294 of build.gradle: `CreateProcessError=2, the system cannot find the file specified`

### Steps to Reproduce:
Build the Main branch in Intellij with JDK 8u0_221

**Comment by SebaSphere** [comment]
Hi! Support for building any of GC's builds will not be supported as GC is currently in prealpha. Please read our README.md, which you can find here: https://github.com/TeamGalacticraft/Galacticraft/blob/main/README.md 🙂

If you get this compiled, please don't hesitate to report any in-game bugs on our issue tracker. Make sure to include the **Galacticraft Build Number** or GC version instead of saying **latest** for the version as this helps us keep track of bugs and gives us a better idea on how to address the bug. Thanks!

**Comment by craftablescience** [comment]
I told them to make this issue @SebaSphere, I figured there was a chance this could be a problem with the repository. They are also looking to help develop the mod, and need it to compile to do that.

**Comment by SebaSphere** [comment]
Ah got it. Thanks for the clarification.

I'll pull this repo again on my laptop where I don't have GC installed.
