### ISSUE TITLE
Issue causing crash on self hosted server. 

### ISSUE THREAD

**Issue by tartletboy** [TeamGalacticraft/Galacticraft#9]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version ("latest" is not a valid option): 1.12.2-4.0.2.281

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?   Self hosted server using ftb revelations modpack as base. Forge is used but that should be it. 
- If MP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them: None

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: https://pastebin.com/iibPMXh9

Please provide screenshots / videos / full modlist as needed: Everything is outlined in the crash report but I think its important to note the server crashes only after someone logs in. this has happened twice so far approximately 5-10 mins after someone initiates a log in. 

Please state the site that you downloaded Galacticraft from: http://micdoodle8.com/mods/galacticraft/downloads
[crash-2020-12-14_14.40.00-server.txt](https://github.com/TeamGalacticraft/Galacticraft/files/5692421/crash-2020-12-14_14.40.00-server.txt)

**Comment by ROMVoid95** [comment]
`java.lang.Error: ServerHangWatchdog detected that a single server tick took 500.00 seconds (should be max 0.05)`

Your crash is caused by the ServerHangWatchdog. The amount of ticks it waits until before it crashes the server (what its made to do) is changeable by the `max-tick-time` option in `server.properties`

[More Info on `max-tick-time`](https://minecraft.gamepedia.com/Server.properties#:~:text=The%20maximum%20number%20of%20milliseconds,is%20met%2C%20it%20calls%20System.)

Galacticraft doesn't even show up in the -- Thread Dump -- output. Set the `max-tick-time` higher or disable and you might simply fix the crashing, and/or find the cause of the lag. Also, unless you have a high amount of players playing at once, 24GB seems a bit excessive for RAM. If not, Allocating too much RAM can cause issues in Java. Something that may be  worth looking into.

**Comment by tartletboy** [comment]
i did increase it previously to that higher number because it was causing issues when it would time out at 60s. The line at `net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185890_d(BlockStateContainer.java:446)`
points to Galacticraft when I searched it on google so I assumed that container was part of GC. I'll try to lower the RAM but according to my task manager and AMP log im using about half of that with 4 people online.

**Comment by ROMVoid95** [comment]
from the Thread Dump logs my best guess is IC2 is causing the issue. Maybe try using the latest version of IC2. But nothing from this shows Galacticraft as any part of the cause.

**Comment by tartletboy** [comment]
ill give it a shot and I guess ill reopen if I find a bug in GC. Thanks!
